import { Doctor } from "./types";

export const DOCTORS: Doctor[] = [
  {
    id: "d1",
    name: "Dr. Amara Osei",
    specialty: "Cardiologist",
    rating: 4.9,
    reviews: 312,
    experience: 15,
    avatar: "AO",
    available: true,
    nextSlot: "Today, 2:00 PM",
    slots: ["09:00", "10:00", "11:00", "14:00", "15:00", "16:00"],
    bio: "Leading cardiologist specialising in preventive heart care and complex cardiac interventions.",
    tags: ["Heart Health", "ECG", "Hypertension"],
  },
  {
    id: "d2",
    name: "Dr. Lena Fischer",
    specialty: "Dermatologist",
    rating: 4.8,
    reviews: 198,
    experience: 10,
    avatar: "LF",
    available: true,
    nextSlot: "Today, 3:30 PM",
    slots: ["08:30", "10:30", "13:00", "15:30", "16:30"],
    bio: "Expert in medical and cosmetic dermatology with a focus on skin cancer screening.",
    tags: ["Skin Care", "Acne", "Cosmetic"],
  },
  {
    id: "d3",
    name: "Dr. Marcus Chen",
    specialty: "Neurologist",
    rating: 4.7,
    reviews: 245,
    experience: 12,
    avatar: "MC",
    available: false,
    nextSlot: "Tomorrow, 9:30 AM",
    slots: ["09:30", "11:30", "13:30", "14:30", "16:00"],
    bio: "Specialist in neurological disorders, headaches, and neuro-rehabilitation programmes.",
    tags: ["Migraines", "Epilepsy", "Stroke"],
  },
  {
    id: "d4",
    name: "Dr. Sana Mirza",
    specialty: "Pediatrician",
    rating: 4.9,
    reviews: 421,
    experience: 8,
    avatar: "SM",
    available: true,
    nextSlot: "Today, 11:00 AM",
    slots: ["08:00", "09:00", "10:00", "11:00", "14:00"],
    bio: "Passionate about children's health from newborn care through adolescent development.",
    tags: ["Newborn", "Vaccines", "Growth"],
  },
  {
    id: "d5",
    name: "Dr. James Okafor",
    specialty: "General Physician",
    rating: 4.6,
    reviews: 533,
    experience: 18,
    avatar: "JO",
    available: true,
    nextSlot: "Today, 4:00 PM",
    slots: ["08:30", "09:30", "11:00", "13:00", "15:00"],
    bio: "Comprehensive primary care physician providing holistic, patient-centred healthcare.",
    tags: ["Primary Care", "Checkups", "Referrals"],
  },
  {
    id: "d6",
    name: "Dr. Priya Nair",
    specialty: "Psychiatrist",
    rating: 4.8,
    reviews: 167,
    experience: 11,
    avatar: "PN",
    available: true,
    nextSlot: "Tomorrow, 10:00 AM",
    slots: ["10:00", "11:00", "13:00", "14:00", "16:00"],
    bio: "Compassionate mental health specialist combining CBT, medication management and mindfulness.",
    tags: ["Anxiety", "Depression", "CBT"],
  },
  {
    id: "d7",
    name: "Dr. Kofi Mensah",
    specialty: "Orthopedist",
    rating: 4.7,
    reviews: 289,
    experience: 14,
    avatar: "KM",
    available: false,
    nextSlot: "Wed, 9:00 AM",
    slots: ["09:00", "11:00", "14:00", "15:00", "16:30"],
    bio: "Sports medicine and joint replacement specialist helping patients return to full mobility.",
    tags: ["Joints", "Sports", "Surgery"],
  },
  {
    id: "d8",
    name: "Dr. Aisha Bello",
    specialty: "Gynecologist",
    rating: 4.9,
    reviews: 376,
    experience: 16,
    avatar: "AB",
    available: true,
    nextSlot: "Today, 2:30 PM",
    slots: ["08:00", "10:00", "12:00", "14:30", "16:00"],
    bio: "Women's health specialist providing prenatal care, family planning and gynaecological surgery.",
    tags: ["Prenatal", "Family Planning", "Surgery"],
  },
];

export const SPECIALTIES = [
  "All",
  ...Array.from(new Set(DOCTORS.map((d) => d.specialty))),
];

export const STATS = [
  { value: "12,400+", label: "Patients Treated", icon: "👤" },
  { value: "98%", label: "Satisfaction Rate", icon: "⭐" },
  { value: "48+", label: "Specialists", icon: "🩺" },
  { value: "24/7", label: "Support Available", icon: "🕐" },
];

export const SPECIALTIES_GRID = [
  { icon: "❤️", label: "Cardiology", count: 8 },
  { icon: "🧠", label: "Neurology", count: 6 },
  { icon: "🦷", label: "Dentistry", count: 12 },
  { icon: "👁", label: "Ophthalmology", count: 5 },
  { icon: "🦴", label: "Orthopedics", count: 9 },
  { icon: "🧬", label: "Dermatology", count: 7 },
  { icon: "👶", label: "Pediatrics", count: 10 },
  { icon: "🧘", label: "Psychiatry", count: 6 },
];
